### ISSUE TITLE
[1505201056] Password recovery manager tidak berfungsi

### ISSUE THREAD

**Issue by asokawardhana** [antonraharja/voip-id#10]
Cara ceknya 
Masuk ke teleponrakyat.id, lalu daftar baru, setelah berhasil coba login, setelah itu logout, dan coba password recovery.

Hal ini berlaku untuk manager yang sudah terdaftar sebelumnya

![uploads/22904287-70a0-4036-9c3d-c7561a309291/Screenshot from 2015-05-20 10:53:41.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F22904287-70a0-4036-9c3d-c7561a309291%2FScreenshot+from+2015-05-20+10%3A53%3A41.png)

**Comment by antonraharja** [comment]
@asokawardhana karena sudah ada nomor issue nya maka tidak perlu lagi pakai [kode]

**Comment by antonraharja** [comment]
jangan di close sendiri ya

**Comment by antonraharja** [comment]
salah, ngga apa2 close sehabis commit, karena emang dia close dengan sendirinya saat commit pakai hash-issue-number.
