### ISSUE TITLE
API onlinephone

### ISSUE THREAD

**Issue by antonraharja** [antonraharja/voip-id#11]
Referensi API: https://github.com/antonraharja/book-voip-id/tree/master/book-contents/en/Development/API

Buatkan API untuk mendapatkan daftar onlinephone

**Comment by antonraharja** [comment]
udah sampe mana progress nya, gmn timeline nya ? ( baca: kapan selesai :) )

**Comment by awangga** [comment]
token menggununakan method post dengan nama variable token

**Comment by antonraharja** [comment]
@asokawardhana coba di implement kep, seru nih kek nya :)

**Comment by awangga** [comment]
oh iya ini aksesnya pake url.dcp/api/verbnyaapi

**Comment by antonraharja** [comment]
contoh lengkap kalo pakai token bagaimana ? misal dcp nya: telepon.ngoprek.org

**Comment by antonraharja** [comment]
contoh dcp telepon.ngoprek.org, maka:

HTTP POST ke `http://telepon.ngoprek.org/api/onlinephone` dengan variable `token` diisi token account

begitu ya?

**Comment by awangga** [comment]
kalo berdasarkan dokumen HTTP POST ke url http://telepon.ngoprek.org/api/onlinephone/list
kalo http://telepon.ngoprek.org/api/onlinephone menghasilkan error

**Comment by antonraharja** [comment]
ok, sip
