### ISSUE TITLE
CDR, add search by time

### ISSUE THREAD

**Issue by antonraharja** [antonraharja/voip-id#7]

**Comment by antonraharja** [comment]
![screen_shot_2015-05-07_at_9 35 42_am](https://cloud.githubusercontent.com/assets/432195/7584631/fb3c3f90-f8c8-11e4-909c-50c96c17ef0c.png)

**Comment by awangga** [comment]
sudah di add

**Comment by antonraharja** [comment]
ntar yang close orang lain ya, jangan diri sendiri, biar di test dulu, minimal diperiksa. saat commit harus menyertakan hash nomor issue misal, misal ini issue nomor 7, maka saat commit tambahkan `#7`, misal: `git commit -m 'fix #7 add time in CDR'`

**Comment by awangga** [comment]
okey siap
