### ISSUE TITLE
[1505131055] Admin edit Manager, lalu back error

### ISSUE THREAD

**Issue by asokawardhana** [antonraharja/voip-id#8]
![uploads/2f8d65a8-90d6-458d-a56f-fd4b20b8f7eb/Screenshot from 2015-05-13 10:52:24.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F2f8d65a8-90d6-458d-a56f-fd4b20b8f7eb%2FScreenshot+from+2015-05-13+10%3A52%3A24.png)

**Comment by antonraharja** [comment]
nah begini aja, emang issue otomatis closed kalo pake hash saat commit, jadi ngga apa2 close sendiri, tapi harus pindahkan ke Done (via huboard)

**Comment by awangga** [comment]
sip kang. masih agak rusuh nih huboardnya, maklum cupu
